# Site settings
title: Jedediah
email: email@domain.poop
url: https://jedypod.com
skills: "Cerebellar Exocarp"

# Color settings (hex-codes without the leading hash-tag)
color:
  base: 6F6960

  primary: 00ff00 #nav bar rollover 
  secondary: ffffaa # navbar background; text color
  secondary-dark: 6F6960 #background colors on secondary pages





  primary-rgb: "255, 00, 00" 
  primary-dark: ff0000

  
  
  link: ff0000
  hover: ff0000
  text: ff0000
  background: ff0000
  nav: ff0000

# Footer settings
footer:
  copyright: Jed Smith

social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jedypod
  - title: 500px
    url: poop
  - title: flickr
    url: poop

# Build settings
markdown: kramdown
permalink:   /:categories/:title/

gems:
  - jekyll-gist

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]