# Site settings
title: Jedediah
email: email@domain.poop
url: https://jedypod.com
description: "This is the header description."
skills: "This is the Header Subtext"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 36373B 
  primary-rgb: "54, 55, 59" #"128,179,255"
  secondary: 36373B
  secondary-dark: 151620
  link:
  hover:
  text: D9DADB



# Footer settings
footer:
  copyright: Jed Smith
  location: PoopyTown
  social: Internet Presence
  credits: credits?

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Don't put your postal Address Online?
  - line: line2

# Credits content
credits: 'Why is this here?'

# Build settings
markdown: kramdown
# permalink: pretty
permalink:   /:categories/:title/
