# Site settings
title: Jedediah
email: email@domain.poop
url: https://jedypod.com
skills: "Cerebellar Exocarp"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff #nav bar rollover 
  secondary: ffffff # navbar background; text color
  secondary-dark: ffffff #background colors on secondary pages

  primary-rgb: "255, 255, 255"  # not sure what this is
  primary-dark: ffffff

  background: 423C32

  link: 788088
  hover: D0C6B6
  text: D0C6B6
  header:  788088


  navbar: 17202B
  nav-text: 788088
  nav-text-rollover: 5A626A


# Footer settings
footer:
  copyright: Jed Smith

social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jedypod
  - title: 500px
    url: poop
  - title: flickr
    url: poop

# Build settings
markdown: kramdown
permalink:   /:categories/:title/

gems:
  - jekyll-gist

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]